-- 13_admin_users.sql（后台管理员表；独立于前台 users，用于管理端登录与权限控制）
CREATE TABLE IF NOT EXISTS `admin_users` (
  `id`            BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id`     BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '租户ID',
  `username`      VARCHAR(64) NOT NULL COMMENT '后台登录用户名',
  `password_hash` VARCHAR(255) NOT NULL COMMENT '密码哈希',
  `nickname`      VARCHAR(64) NOT NULL DEFAULT '' COMMENT '显示昵称',
  `email`         VARCHAR(128) NULL COMMENT '邮箱；可为空，避免默认空字符串触发唯一索引冲突',
  `mobile`        VARCHAR(32) NULL COMMENT '手机号；可为空',
  `avatar`        VARCHAR(512) NULL COMMENT '头像地址',
  `status`        TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '状态: 1=active,2=disabled,3=deleted,4=locked',
  `is_super_admin` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否超级管理员: 0=否,1=是',
  `password_changed_at` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '最近修改密码时间（秒）',
  `last_login_at` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '最近登录时间（秒）',
  `last_login_ip` VARCHAR(64) NULL COMMENT '最近登录IP',
  `last_login_user_agent` VARCHAR(512) NULL COMMENT '最近登录UA',
  `login_failed_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '连续登录失败次数',
  `locked_until` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '锁定截止时间（秒），0=未锁定',
  `remark`        VARCHAR(255) NOT NULL DEFAULT '' COMMENT '备注',
  `created_at`    BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建时间（秒）',
  `updated_at`    BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新时间（秒）',
  `deleted_at`    BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '软删除时间（秒）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_admin_tenant_username` (`tenant_id`,`username`),
  UNIQUE KEY `uk_admin_tenant_email` (`tenant_id`,`email`),
  KEY `idx_admin_tenant_id` (`tenant_id`),
  KEY `idx_admin_status` (`tenant_id`,`status`),
  KEY `idx_admin_super_admin` (`tenant_id`,`is_super_admin`),
  KEY `idx_admin_last_login_at` (`last_login_at`),
  KEY `idx_admin_locked_until` (`locked_until`),
  KEY `idx_admin_created_at` (`created_at`),
  KEY `idx_admin_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='后台管理员表';